# Pipeline to create a Github release for the CoE Starter Kit solution
parameters:
- name: ReleaseMonthNumber
  type: number
- name: ReleaseYearNumber
  type: number
- name: CloseMilestoneIssues
  type: boolean
  default: false
- name: DraftRelease
  type: boolean
  default: true
- name: HotfixReleaseNumber
  type: number
  default: 0
- name: PrepareAppSourcePackage
  type: boolean
  default: false
- name: PreparePackageDeployerPackage
  type: boolean
  default: false
  
trigger: none
pr: none
resources:
  repositories:
  - repository: PipelineRepo  # repository name (DO NOT CHANGE THIS VALUE) 
    type: github
    ref: Rajeev-ts-release #main # If your pipeline templates are in a branch other than the default branch specify the branch here. Otherwise the default branch will be used by default.
    endpoint: powercat-alm # Specifies the GitHub service connection for this setup.
    name: Microsoft/coe-alm-accelerator-templates  #This is the name of the repo in the current project in Azure Devops that has the pipeline templates. If the repo is in a different project you can specify the project and repo using the format ProjectContainingTheBuildTemplates/RepositoryContainingTheBuildTemplates (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#type)
pool:
  vmImage: 'windows-2019'

variables:
- group: alm-accelerator-variable-group

steps:
# Checkout our GitHub Branch
- checkout: self
  displayName: 'Checkout Source Branch'

- powershell: |
    New-Item -Path $(Pipeline.Workspace)\releaseassets -ItemType Directory -Force
    New-Item -Path $(Pipeline.Workspace)\assetstaging -ItemType Directory -Force

    # Copy managed ZIP with original name to staging (will rename later)
    Copy-Item '$(Pipeline.Workspace)\drop\*managed.zip' -Destination '$(Pipeline.Workspace)\assetstaging'

    # Copy static release resources
    Copy-Item '$(Build.SourcesDirectory)\Power-CAT-Copilot-Studio-Kit\CopilotstudioAcceleratorResources\Release\Collateral\CopilotstudioAccelerator\*.*' -Destination '$(Pipeline.Workspace)\assetstaging'

    # Compress to: CopilotStudioKit.zip
    $compress = @{
      Path = '$(Pipeline.Workspace)\assetstaging\*.*'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)\releaseassets\CopilotStudioKit.zip'
    }
    Compress-Archive @compress

    # Copy managed zip again to releaseassets for renaming (original name includes build number)
    Copy-Item '$(Pipeline.Workspace)\drop\*managed.zip' -Destination '$(Pipeline.Workspace)\releaseassets'

    # Cleanup
    Remove-Item $(Pipeline.Workspace)\drop\*managed.zip -Recurse -Force -Confirm:$false
    Remove-Item $(Pipeline.Workspace)\assetstaging -Recurse -Force -Confirm:$false
    New-Item -Path $(Pipeline.Workspace)\assetstaging -ItemType Directory -Force

    # Copy unmanaged version for second archive
    Copy-Item '$(Pipeline.Workspace)/drop/CopilotStudioAccelerator*.zip' -Destination '$(Pipeline.Workspace)\assetstaging'

    # Compress to: CopilotStudioKit-Unmanaged.zip
    $compress = @{
      Path = '$(Pipeline.Workspace)\assetstaging\*.*'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)/releaseassets/CopilotStudioKit-Unmanaged.zip'
    }
    Compress-Archive @compress

    # Rename managed solution file with build number
    Get-ChildItem '$(Pipeline.Workspace)\releaseassets\CopilotStudioAccelerator*_managed.zip' | ForEach-Object {
      $newName = $_.Name -replace '^CopilotStudioAccelerator', 'CopilotStudioKit'
      Rename-Item $_.FullName -NewName $newName
    }

    # Set release metadata
    $templateTag = 'CopilotStudioKit-$(ReleaseMonthName)${{parameters.ReleaseYearNumber}}'
    $templateTitle = 'Copilot Studio Kit $(ReleaseMonthName) ${{parameters.ReleaseYearNumber}}'
    if(${{parameters.HotfixReleaseNumber}} -ne 0) {
        $templateTag = 'CopilotStudioKit-$(ReleaseMonthName)${{parameters.ReleaseYearNumber}}-HF${{parameters.HotfixReleaseNumber}}'
        $templateTitle = 'Copilot Studio Kit $(ReleaseMonthName) ${{parameters.ReleaseYearNumber}} - Hotfix ${{parameters.HotfixReleaseNumber}}'
    }
    Write-Host "##vso[task.setvariable variable=TemplateTag]$templateTag"
    Write-Host "##vso[task.setvariable variable=TemplateTitle]$templateTitle"
  displayName: 'Prepare release assets'

- template: Pipelines\Templates\create-release-github.yml@PipelineRepo
  parameters:
    gitHubApiUrl: 'microsoft/Power-CAT-Copilot-Studio-Kit'
    solutionName: 'CopilotStudioAccelerator'
    solutionDisplayName: 'Copilot Studio Accelerator'
    releaseMonth: ${{parameters.ReleaseMonthNumber}}
    releaseYear: ${{parameters.ReleaseYearNumber}}
    connectionName: 'powercat-alm'
    releaseNotesPath: 'Power-CAT-Copilot-Studio-Kit/CopilotstudioAcceleratorResources/Release/Notes/'
    issueClosingComment: 'This has been fixed in the latest release.'
    closeIssues: ${{parameters.CloseMilestoneIssues}}
    isDraft: ${{parameters.DraftRelease}}
    isPreRelease: false
    hotfixReleaseNumber: ${{parameters.HotfixReleaseNumber}}
    queryHeadingDelimited: ""
    prepareAppSourcePackage: ${{parameters.PrepareAppSourcePackage}}
    preparePackageDeployerPackage: ${{parameters.PreparePackageDeployerPackage}}
    projectName: "Power-CAT-Copilot-Studio-Kit"
    packageConfigurationFilePath: "Power-CAT-Copilot-Studio-Kit/PowerCAT.PackageDeployer.Package/PowerCAT.Package.Settings.json"
